name: Docker CI/CD

on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t my-node-app .
          docker tag my-node-app:latest sathishvisar/my-image-name:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push sathishvisar/my-image-name:latest

      - name: Prepare SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # This should contain your private key
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key

      - name: Deploy to Docker server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH key directly
          source: "deploy.sh"
          target: "/home/ec2-user/deploy.sh"  # Target path on the server
