name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          chmod 600 deploy_key
          ssh-keyscan -H 13.60.98.236 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key ec2-user@13.60.98.236 << 'EOF'
            cd /home/ec2-user/aws-docker-s3
            git pull origin master
            npm install
            pm2 restart app --update-env
          EOF

      - name: Cleanup
        run: rm deploy_key
