name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 16.171.32.93 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ec2-user@16.171.32.93 << 'EOF'
            cd /home/ec2-user/aws-docker-s3
            git pull origin master
            npm install
            pm2 restart app --update-env
          EOF

      - name: Cleanup
        run: rm ~/.ssh/deploy_key
