name: Docker CI/CD

on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t my-node-app .
          docker tag my-node-app:latest sathishvisar/my-image-name:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push sathishvisar/my-image-name:latest

      - name: Decode and prepare SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" | base64 -d > private-key.pem
          chmod 600 private-key.pem

      - name: Deploy to Docker server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: private-key.pem
          script: |
            bash ~/deploy.sh
